---
title: "Aprendizado de Máquina Supervisionado Aplicado à Séries Temporais"
format: html
author: Vinicius Aquino
---



# Resumo

<p></p>
<br>

# Aprendizado de Máquina Supervisionado

<p>O Aprendizado de Máquina Supervisionado é essêncialmente o uso de modelos matemáticos e algoritimos para prever uma resposta <i>y</i> dado um vetor de variáveis $(x_1, x_2, ..., x_n)$, onde tais algoritimos e modelos são treinados a partir de uma amostra onde estas respostas <i>y</i> são previamente conhecidas. Em resumo, o cientista de dados tem um conjunto de dados com as devidas respostas e treina um modelo para aprender a variável alvo dele. A partir daí, aplica este modelo para prever em instâncias onde essa tal variável alvo é desconhecida.</p>
<br>

## Regressão 

<p>Regressões são uma família de modelos de aprendizado de máquina supervisionado. Na verdade, como será abordado algumas extensões de modelos de regressão aqui, pode-se dizer que a linha que separa é um tanto nebulosa. A idéia de uma regressão é criar uma <i>função</i> que descreva uma certa <i>quantidade</i> de uma variável alvo. 
$$Q(y) = $$
</p>
<br>

### Linear vs Não Linear 

<p></p>
<br>

### Paramétrica vs Não Paramétrica 

<p></p>
<br>


# Séries Temporais

<p></p>$$
<br>

# Hands-on: Especificando Modelos

<p></p>
<br>

# Deployment


